# OOPs

In [7]:
class phone:
    def behave(self):
        print("this is good")

In [8]:
p1 = phone()

In [9]:
p1.behave()

this is good


In [18]:
class phone:
    def color(self,color):
        self.color = color
       

In [19]:
p1 = phone()

In [23]:
c



TypeError: 'str' object is not callable

In [27]:
class student:
    def __init__(self,sid,name,age,salary):
        self.sid = sid
        self.name = name
        self.age=age
        self.salary = salary
    def show(self):
        print("Student id = ",self.sid)
        print("Student Name = ",self.name)
        print("Student Age = ",self.age)
        print("Student salary = ",self.salary)
       

In [28]:
s = student(1,"ram",12,12000)

In [29]:
s.show()

Student id =  1
Student Name =  ram
Student Age =  12
Student salary =  12000


In [30]:
import numpy as np

In [31]:
a = np.array(20)
a

array(20)

In [33]:
a= np.array([10,20,30])

In [34]:
a

array([10, 20, 30])

In [36]:
a= np.array([[10,20,30],[20,30,25]])
a

array([[10, 20, 30],
       [20, 30, 25]])

In [37]:
b = np.ndim

In [39]:
n1 =np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
n1 =np.full((5,5),5)
n1

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [45]:
a= np.array([[10,20,30],[20,30,25],[25,26,10]])
a = a+5
a

array([[15, 25, 35],
       [25, 35, 30],
       [30, 31, 15]])

In [46]:
a= np.array([[10,20,30],[20,30,25],[25,26,10]])
a = a-5
a

array([[ 5, 15, 25],
       [15, 25, 20],
       [20, 21,  5]])

In [47]:
a= np.array([[10,20,30],[20,30,25],[25,26,10]])
a = a*5
a

array([[ 50, 100, 150],
       [100, 150, 125],
       [125, 130,  50]])

In [48]:
a= np.array([[10,20,30],[20,30,25],[25,26,10]])
a = a/5
a

array([[2. , 4. , 6. ],
       [4. , 6. , 5. ],
       [5. , 5.2, 2. ]])

In [51]:
n2 = np.arange(10,20)
n2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
n2 = np.arange(10,20,3)
n2

array([10, 13, 16, 19])

In [55]:
n1 = np.array([12,12,23,34,45])
n2 = np.array([34,21,22,43,22])
n2

array([34, 21, 22, 43, 22])

In [58]:
np.vstack((n1,n2))

array([[12, 12, 23, 34, 45],
       [34, 21, 22, 43, 22]])

In [59]:
np.hstack((n1,n2))

array([12, 12, 23, 34, 45, 34, 21, 22, 43, 22])

In [60]:
np.column_stack((n1,n2))

array([[12, 34],
       [12, 21],
       [23, 22],
       [34, 43],
       [45, 22]])

In [3]:
import numpy as np
n1 = np.array([12,12,23,34,45])
n2 = np.array([34,21,22,43,22])
n3 = np.setdiff1d(n1,n2)
n3

array([12, 23, 45])

In [4]:
n1 = np.array([12,12,23,34,45])
n2 = np.array([34,21,22,43,22])
n3 = np.setdiff1d(n2,n1)
n3

array([21, 22, 43])

In [5]:
n1 = np.array([12,12,23,34,45])
n2 = np.array([34,21,22,43,22])
n3 = np.intersect1d(n1,n2)
n3

array([34])