In [1]:
import numpy as np

In [2]:
a = np.array(10)
A

NameError: name 'A' is not defined

In [3]:
a

array(10)

In [6]:
print((a.ndim))

0


In [7]:
a=np.array([12,23,34,45])
a

array([12, 23, 34, 45])

In [8]:
print(a.ndim)

1


In [10]:
a=np.array([[12,23,34,45],[12,2,34,45]])
a

array([[12, 23, 34, 45],
       [12,  2, 34, 45]])

In [11]:
a=np.array([[[12,23,34,45],[12,2,34,45],[2,3,4,5],[45,56,78,9]]])
a

array([[[12, 23, 34, 45],
        [12,  2, 34, 45],
        [ 2,  3,  4,  5],
        [45, 56, 78,  9]]])

In [12]:
print(a.ndim)

3


In [13]:
a=np.array([[12,23,34,45],[12,2,34,45]])
a[1]

array([12,  2, 34, 45])

In [15]:
a=np.array([[12,23,34,45],[12,2,34,45]])
a[0]

array([12, 23, 34, 45])

In [16]:
a=np.array([[12,23,34,45],[12,2,34,45]])
a[0 , 1]

23

In [17]:
a[1,1:3]

array([ 2, 34])

In [18]:
a[0::4]

array([[12, 23, 34, 45]])

In [24]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c= np.vstack((a,b))
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c= np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c= np.column_stack((a,b))
c

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
d=np.setdiff1d(a,b)
d

array([1, 2, 3, 4])

In [37]:
a = np.array([12,23,34,45,33])
b=a.copy()
a[0]=27
print(a)
print(b)

[27 23 34 45 33]
[12 23 34 45 33]


In [40]:
a = np.array([12,23,34,45,33])
b=a.view()
a[0]=27
b[0]=10000
print(a)
print(b)

[10000    23    34    45    33]
[10000    23    34    45    33]


In [46]:
f = np.array([12,23,34,45,33])
f
print(f.shape)

(5,)


In [49]:
f = np.array([12,23,34,45,33])
d=f.reshape(2,2)
print(d)

ValueError: cannot reshape array of size 5 into shape (2,2)